### ISSUE TITLE
Only opens partials designed with the new format hash, but not the old format

### ISSUE THREAD

**Issue by blschill** [dewski/open-rails-partial-vscode-extension#2]
For example:

render partial: "test_partial" would open on GoTo Definition
BUT
render :partial => "test_partial" would show no definition for "test_partial"

**Comment by dewski** [comment]
Could you share more context on what the issue is? This VS Code extension exposes a VS Code URI handler to open the partial files detected by the [Chrome extension](https://github.com/dewski/open-rails-partial-chrome-extension). The Chrome extension gets the partial path directly from the HTML comments rendered by Rails. This would work for any hash format, or even no hash provided (`render "test_partial"`).

Going to close for now, but please re-open if there is an issue with the VS Code extension regarding opening partials.
